<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.28" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.28">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hallen.Common\Hallen.Common.csproj" />
		<ProjectReference Include="..\Hallen.Database\Hallen.Database.csproj" />
		<ProjectReference Include="..\Hallen.Application\Hallen.Application.csproj" />
	</ItemGroup>

</Project>
