// <auto-generated />
using System;
using Hallen.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hallen.Database.Migrations
{
    [DbContext(typeof(HallenDbContext))]
    [Migration("20260531094435_AddNameToGameMatches")]
    partial class AddNameToGameMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hallen.Database.Models.GameMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer")
                        .HasColumnName("match_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId", "MatchNumber")
                        .IsUnique();

                    b.ToTable("game_matches", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.GameMatchTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameMatchId", "GameTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GameMatchTeamPlayers");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameMatchTeamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_match_id");

                    b.Property<Guid>("GameTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_team_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("GameTeamId");

                    b.HasIndex("GameMatchId", "GameTeamId")
                        .IsUnique();

                    b.ToTable("game_match_team_results", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SportsGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("sports_group_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex("SportsGroupId");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.GameSessionPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameSessionId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GameSessionPlayers");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("game_teams", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.GameTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_team_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("game_team_players", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SportsGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("sports_group_id");

                    b.HasKey("Id");

                    b.HasIndex("SportsGroupId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.SportsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("sports_groups", (string)null);
                });

            modelBuilder.Entity("Hallen.Database.Models.GameMatch", b =>
                {
                    b.HasOne("Hallen.Database.Models.GameSession", "GameSession")
                        .WithMany("GameMatches")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameMatchTeamPlayer", b =>
                {
                    b.HasOne("Hallen.Database.Models.GameMatch", "GameMatch")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("GameMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hallen.Database.Models.GameTeam", "GameTeam")
                        .WithMany("GameMatchTeamPlayers")
                        .HasForeignKey("GameTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hallen.Database.Models.Player", "Player")
                        .WithMany("GameMatchTeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameMatch");

                    b.Navigation("GameTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameMatchTeamResult", b =>
                {
                    b.HasOne("Hallen.Database.Models.GameMatch", "GameMatch")
                        .WithMany("TeamResults")
                        .HasForeignKey("GameMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hallen.Database.Models.GameTeam", "GameTeam")
                        .WithMany("GameMatchTeamResults")
                        .HasForeignKey("GameTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameMatch");

                    b.Navigation("GameTeam");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameSession", b =>
                {
                    b.HasOne("Hallen.Database.Models.SportsGroup", "SportsGroup")
                        .WithMany("GameSessions")
                        .HasForeignKey("SportsGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SportsGroup");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameSessionPlayer", b =>
                {
                    b.HasOne("Hallen.Database.Models.GameSession", "GameSession")
                        .WithMany("GameSessionPlayers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hallen.Database.Models.Player", "Player")
                        .WithMany("GameSessionPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameTeam", b =>
                {
                    b.HasOne("Hallen.Database.Models.GameSession", "GameSession")
                        .WithMany("GameTeams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameTeamPlayer", b =>
                {
                    b.HasOne("Hallen.Database.Models.GameTeam", "GameTeam")
                        .WithMany("GameTeamPlayers")
                        .HasForeignKey("GameTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hallen.Database.Models.Player", "Player")
                        .WithMany("GameTeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Hallen.Database.Models.Player", b =>
                {
                    b.HasOne("Hallen.Database.Models.SportsGroup", "SportsGroup")
                        .WithMany("Players")
                        .HasForeignKey("SportsGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SportsGroup");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameMatch", b =>
                {
                    b.Navigation("TeamPlayers");

                    b.Navigation("TeamResults");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameSession", b =>
                {
                    b.Navigation("GameMatches");

                    b.Navigation("GameSessionPlayers");

                    b.Navigation("GameTeams");
                });

            modelBuilder.Entity("Hallen.Database.Models.GameTeam", b =>
                {
                    b.Navigation("GameMatchTeamPlayers");

                    b.Navigation("GameMatchTeamResults");

                    b.Navigation("GameTeamPlayers");
                });

            modelBuilder.Entity("Hallen.Database.Models.Player", b =>
                {
                    b.Navigation("GameMatchTeamPlayers");

                    b.Navigation("GameSessionPlayers");

                    b.Navigation("GameTeamPlayers");
                });

            modelBuilder.Entity("Hallen.Database.Models.SportsGroup", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
